"""Pydantic models matching DynamoDB schemas exactly (Section 5)."""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel


# ── 5.1 Tenants ──────────────────────────────────────────────
class Tenant(BaseModel):
    tenant_id: str
    agency_name: str
    admin_email: str
    status: str  # active | suspended | trial
    plan: str  # trial | starter | pro
    provider_type: str  # twilio | ringcentral | zoom | teams | 8x8
    deployment_tier: str  # beta | live_test | full
    created_at: str  # ISO 8601
    updated_at: str  # ISO 8601
    twilio_account_sid: Optional[str] = None
    twilio_phone_number: Optional[str] = None


# ── 5.2 Agents ───────────────────────────────────────────────
class Agent(BaseModel):
    tenant_id: str
    agent_id: str
    email: str
    name: str
    status: str  # invited | active | inactive
    cognito_sub: Optional[str] = None
    created_at: str
    invited_at: str
    confirmed_at: Optional[str] = None


# ── 5.3 Number Mappings ─────────────────────────────────────
class NumberMapping(BaseModel):
    tenant_id: str
    identifier: str  # +15551234567 | ext:204 | email:user@co.com
    agent_id: str
    identifier_type: str  # did | extension | email | sip
    label: str
    created_at: str


# ── 5.4 Calls ────────────────────────────────────────────────
class Call(BaseModel):
    tenant_id: str
    call_id: str
    agent_id: Optional[str] = None
    provider: str  # twilio | ringcentral | zoom | teams | 8x8
    provider_call_id: str
    direction: str  # inbound | outbound
    from_number: str  # E.164
    to_identifier: str
    duration_sec: int
    status: str  # recording | transcribing | summarizing | complete | failed
    recording_s3_key: Optional[str] = None
    transcript_s3_key: Optional[str] = None
    transcript_status: Optional[str] = None  # pending | in_progress | complete | failed
    summary: Optional[str] = None
    action_items: Optional[list] = None
    notes: Optional[str] = None
    notes_updated_at: Optional[str] = None
    created_at: str
    ended_at: Optional[str] = None
    # Synthetic attribute for agent-date-index GSI
    agent_date_key: Optional[str] = None


# ── 5.5 WebSocket Connections ────────────────────────────────
class WSConnection(BaseModel):
    connection_id: str
    agent_id: str
    tenant_id: str
    connected_at: str
    ttl: int  # Unix timestamp


# ── 5.6 Feature Flags ───────────────────────────────────────
class FeatureFlag(BaseModel):
    flag_name: str
    enabled_tiers: list  # e.g. ['beta', 'live_test', 'full']
    description: str
    default_value: bool
    updated_at: str


# ── 5.7 Deployments ─────────────────────────────────────────
class Deployment(BaseModel):
    deployment_id: str
    git_sha: str
    git_tag: str
    lambda_version: str
    alias: str  # CANARY | LIVE
    status: str  # canary | live_test | full | rolled_back
    error_rate_at_deploy: Optional[float] = None
    deployed_at: str
    promoted_at: Optional[str] = None
    rolled_back_at: Optional[str] = None
    deployed_by: str


# ── 7.2 NormalizedCallEvent ──────────────────────────────────
class NormalizedCallEvent(BaseModel):
    tenant_id: str
    provider: str  # twilio | ringcentral | zoom | teams | 8x8
    provider_call_id: str
    direction: str  # inbound | outbound
    from_number: str  # E.164
    to_identifier: str
    duration_sec: int
    recording_url: str
    recording_format: str  # mp3 | wav | ogg
    ended_at: datetime
    raw_payload: dict

    # ── Teams-specific fields (spec §10 + §5.7) ───────────────
    # All default to the "non-Teams" values so existing adapters
    # (twilio, ringcentral, zoom, 8x8) do not need to change.
    #
    # Note: §10 of the spec explicitly lists five fields (the block
    # starting at recording_already_uploaded). §5.7 shows the full
    # wire format the Teams bot sends, which includes three more —
    # call_id, agent_id, ms_call_id. §10 under-specified the model;
    # these three are added here to match what §5.7 requires the
    # SQS message to carry. Approved explicitly by product owner
    # before this edit (spec gap, not invention).

    call_id: Optional[str] = None
    # Pre-generated by the TeamsMediaBot at call-answer time and used
    # when the bot creates the DynamoDB call record in §5.6.5. When
    # populated, RecordingProcessor must reuse this call_id (not
    # generate its own via uuid4) so the subsequent UPDATE hits the
    # existing record. All non-Teams adapters leave this None, in
    # which case RecordingProcessor falls back to its existing
    # uuid4 generation.

    agent_id: Optional[str] = None
    # Pre-resolved by the TeamsMediaBot via the ms-user-index GSI on
    # sotto-agents (ms_user_id → agent_id lookup, spec §5.8). For
    # Teams, RecordingProcessor trusts this value and does NOT call
    # _resolve_agent() (which is phone-number based and meaningless
    # for Teams calls). Non-Teams providers leave None and go through
    # the number-mapping resolver as before.

    ms_call_id: Optional[str] = None
    # Microsoft Teams' opaque call identifier. Stored on the call
    # record for cross-referencing with Teams Admin Center, support
    # debugging, and future Graph API queries. Populated only for
    # Teams; None for all other providers.

    recording_already_uploaded: bool = False
    # True when the TeamsMediaBot already uploaded the stereo MP3 to S3
    # and populated recording_s3_key directly. RecordingProcessor uses
    # this flag to SKIP its normal provider-URL download step (spec §9
    # Change 1) and to UPDATE the existing call record rather than
    # CREATE a new one (spec §9 Change 2 — the bot already created the
    # record the moment it answered the call, per §5.6.5). Always False
    # for non-Teams providers — they go through the standard
    # download-from-provider-URL path.

    recording_s3_key: Optional[str] = None
    # Populated by TeamsMediaBot when recording_already_uploaded=True.
    # Format: {tenant_id}/recordings/{year}/{month}/{call_id}.mp3
    # Non-Teams providers leave this None; RecordingProcessor computes
    # the key itself after downloading from the provider URL.

    agent_channel: int = 0
    # For stereo Teams recordings: which MP3 channel contains the agent
    # audio. Always 0 for Teams — the bot routes agent audio to channel 0
    # at capture time (spec §5.6.8). Used by TranscriptionResultProcessor
    # to deterministically map ch_0/ch_1 → "agent"/"client" in the
    # transcript. Ignored by all non-Teams providers because their
    # recordings are mono.

    partial: bool = False
    # True if the Teams bot terminated the recording early (SIGTERM
    # graceful shutdown, network loss, bot crash, etc.) — spec §5.6.7.
    # The downstream pipeline still runs on a partial recording: a
    # partial transcript is better than nothing, and the agent can add
    # manual notes for what was missed. RecordingProcessor logs a warning
    # and marks the call record with partial_recording=True.

    partial_reason: Optional[str] = None
    # Why the recording was cut short. One of: None (complete) |
    # "graceful_shutdown" | "network_loss". Stored on the call record
    # for debugging and visible in the admin portal call-detail view.
